Some better logging.

diff --git a/fullstack b/fullstack
--- a/fullstack
+++ b/fullstack
@@ -4,6 +4,8 @@ SCRIPT_DIR="$(cd "$(dirname "$0")" || exit ; pwd -P)"
 # shellcheck source=/dev/null
 source "${SCRIPT_DIR}/common-functions.sh"
 
+cd "${SCRIPT_DIR}" || die "can't change to ${SCRIPT_DIR}"
+
 start_time="$(date -u +%s)"
 log_info "Starting fullstack script"
 log_info "CI branch: ${CI_COMMIT_REF_NAME}"
@@ -23,6 +25,7 @@ if [ -z "${CI_COMMIT_REF_NAME}" ]; then
 fi
 end_time="$(date -u +%s)"
 sync_elapsed="$(($end_time-$start_time))"
+log_info "- Sync done or skipped"
 
 start_time="$(date -u +%s)"
 ./new-quic git-quictls 2>&1
