Also fail the quictls build if the configure fails.

diff --git a/new-quic b/new-quic
--- a/new-quic
+++ b/new-quic
@@ -47,23 +47,28 @@ if [ -e "${QUICTLS_SRC_DIR}" ]; then
     sudo bash -c "$(declare -f do_git_update); do_git_update"
     sudo make -s distclean > /dev/null
     sudo ./config ${CONFARGS}
-    sudo make -s -j ${MAKE_COUNT} > /dev/null
     RETVAL="$?"
     if [ "$RETVAL" -eq 0 ]; then
-      sudo rm -rf /opt/old.quictls
-      sudo mv /opt/quictls /opt/old.quictls
-      sudo make -s install > /dev/null
+      sudo make -s -j ${MAKE_COUNT} > /dev/null
       RETVAL="$?"
       if [ "$RETVAL" -eq 0 ]; then
-        sudo bash -c "$(declare -f add_bin_to_path); add_bin_to_path"
-	sudo rm -rf /opt/quictls/ssl/certs
-        sudo ln -s /etc/ssl/certs /opt/quictls/ssl/certs
-        sudo make -s distclean > /dev/null
+        sudo rm -rf /opt/old.quictls
+        sudo mv /opt/quictls /opt/old.quictls
+        sudo make -s install > /dev/null
+        RETVAL="$?"
+        if [ "$RETVAL" -eq 0 ]; then
+          sudo bash -c "$(declare -f add_bin_to_path); add_bin_to_path"
+          sudo rm -rf /opt/quictls/ssl/certs
+          sudo ln -s /etc/ssl/certs /opt/quictls/ssl/certs
+          sudo make -s distclean > /dev/null
+        else
+          die "Install failed!"
+        fi
       else
-        die "Install failed!"
+        die "Build failed!"
       fi
     else
-      die "Build failed!"
+      die "Configure failed!"
     fi
   else
     die "location (${QUICTLS_SRC_DIR}) is not a directory."
