fix shellcheck stuff.

diff --git a/new-wolfssl b/new-wolfssl
--- a/new-wolfssl
+++ b/new-wolfssl
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-SCRIPT_DIR="$(cd "$(dirname $0)";pwd -P)"
+SCRIPT_DIR="$(cd "$(dirname "$0")" || exit ; pwd -P)"
+# shellcheck source=/dev/null
 source "${SCRIPT_DIR}/functions.sh"
 WOLFSSL_SRC_DIR="${SCRIPT_DIR}/$1"
 MAKE_COUNT="$(make_cpu_count)"
@@ -27,7 +28,7 @@ do_git_update() {
   git pull --rebase 2>&1
 }
 
-CONFARGS="--prefix=/opt/wolfssl --with-gas"
+CONFARGS=(--prefix=/opt/wolfssl --with-gas)
 
 if [ -z "$1" ]; then
   die "Command needs an argument, the subdirectory with wolfssl source"
@@ -35,7 +36,7 @@ fi
 
 if [ -e "${WOLFSSL_SRC_DIR}" ]; then
   if [ -d "${WOLFSSL_SRC_DIR}" ]; then
-    cd ${WOLFSSL_SRC_DIR} || die "Unable to cd to ${WOLFSSL_SRC_DIR}"
+    cd "${WOLFSSL_SRC_DIR}" || die "Unable to cd to ${WOLFSSL_SRC_DIR}"
     info "Updating wolfssl repo"
     sudo -E bash -c "$(declare -f do_git_update); do_git_update"
     info "Cleaning wolfssl repo"
@@ -43,12 +44,12 @@ if [ -e "${WOLFSSL_SRC_DIR}" ]; then
     info "Running autogen"
     sudo -E ./autogen.sh
     info "Configuring wolfssl"
-    sudo -E ./configure ${CONFARGS}
+    sudo -E ./configure "${CONFARGS[@]}"
     RETVAL="$?"
     if [ "$RETVAL" -eq 0 ]; then
       info "Building wolfssl, may take a few minutes"
       info "Using ${MAKE_COUNT} threads with make"
-      sudo -E make -s -j ${MAKE_COUNT}
+      sudo -E make -s -j "${MAKE_COUNT}"
       RETVAL="$?"
       if [ "$RETVAL" -eq 0 ]; then
         sudo -E rm -rf /opt/old.wolfssl
